use_frameworks!

platform :ios, '10.0'

target 'TianyiAVManager_Example' do
  pod 'TianyiAVManager', :path => '../'

  target 'TianyiAVManager_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
